create table if not exists public.hs_search_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  ip_hash text not null,
  user_agent text null,
  query text not null,
  universe text null,
  locale text null,
  status text not null default 'ok'
);

create index if not exists hs_search_logs_ip_created_idx
  on public.hs_search_logs (ip_hash, created_at desc);

create index if not exists hs_search_logs_created_at_idx
  on public.hs_search_logs (created_at desc);

alter table public.hs_search_logs enable row level security;
